#include "raft/RawNode.h"

#include <algorithm>
#include <random>
#include <stdexcept>

namespace raft {

using tracker::Progress;
using tracker::ProgressState;

namespace {

HardState makeHardState(Term t, NodeId v, Index c) {
    HardState hs;
    hs.term   = t;
    hs.vote   = v;
    hs.commit = c;
    return hs;
}

bool isLocalMsg(MessageType t) {
    return t == MessageType::MsgUnreachable ||
           t == MessageType::MsgSnapStatus  ||
           t == MessageType::MsgCheckQuorum;
}

} // namespace

// ============================================================
// Constructor
// ============================================================

RawNode::RawNode(const Config& c)
    : id_(c.id)
    , lead_(c.leaderId)
    , electionTick_(c.electionTick)
    , heartbeatTick_(c.heartbeatTick)
    , log_(c.storage)
    , maxSizePerMsg_(c.maxSizePerMsg)
    , maxInflightMsgs_(c.maxInflightMsgs) {

    readOnly_.setOption(c.readOnlyOption);

    auto init = c.storage->initialState();
    term_ = init.hardState.term;
    vote_ = init.hardState.vote;

    // Bootstrap: if the log is empty, seed voters from Config.peers.
    // Otherwise recover the configuration from persistent state.
    if (c.storage->lastIndex() == 0 && !c.peers.empty()) {
        voters_ = c.peers;
    } else {
        voters_   = init.confState.nodes;
        learners_ = init.confState.learners;
    }
    if (voters_.empty() && !c.peers.empty()) {
        voters_ = c.peers;
    }
    if (learners_.empty() && !c.learners.empty()) {
        learners_ = c.learners;
    }

    // Randomize the first election timeout to avoid split votes.
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<uint32_t> dist(electionTick_, 2 * electionTick_);
    randomizedElectionTick_ = dist(gen);
}

RawNode::~RawNode() = default;

// ============================================================
// Driving the state machine
// ============================================================

bool RawNode::tick() {
    if (role_ == Role::Leader) {
        // Heartbeat every heartbeatTick_ ticks.
        if (++tickCount_ >= heartbeatTick_) {
            tickHeartbeat();
            tickCount_ = 0;
            return true;
        }
        return false;
    }
    return tickElection();
}

void RawNode::tickHeartbeat() {
    broadcastHeartbeat();
}

bool RawNode::tickElection() {
    if (++tickCount_ >= randomizedElectionTick_) {
        campaign();
        tickCount_ = 0;
        return true;
    }
    return false;
}

void RawNode::step(const Message& m) {
    // --- Local messages bypass the term check (etcd pattern) ---
    // These are generated by the transport/loop, not by a remote peer.
    if (m.type == MessageType::MsgUnreachable) {
        auto it = pr_.find(m.from);
        if (it != pr_.end()) {
            it->second.becomeProbe();
        }
        return;
    }
    if (m.type == MessageType::MsgSnapStatus) {
        auto it = pr_.find(m.from);
        if (it == pr_.end()) return;
        if (m.reject) {
            it->second.becomeProbe();
        } else {
            it->second.becomeProbe();
            it->second.matchIndex = it->second.pendingSnapshotIndex;
            it->second.nextIndex  = it->second.matchIndex + 1;
            maybeCommit();
        }
        return;
    }

    // --- Term handling (Figure 3 rules for all servers) ---

    // A message with a higher term: step down to follower.
    // PreVote messages don't update term (thesis Section 9.6).
    if (m.term > term_) {
        if (m.type == MessageType::MsgPreVote || m.type == MessageType::MsgPreVoteResp) {
            // PreVote: don't update term, just process below.
        } else {
            bool wasLeader = (role_ == Role::Leader);
            becomeFollower(m.term, NodeId{0});
            // If we were leader and see a higher term, we already stepped down.
            (void)wasLeader;
        }
    }

    // A message with a lower term than ours: stale, ignore.
    // For some types we send back our term so the sender can step down.
    if (m.term < term_) {
        MessageType t = m.type;
        if (t == MessageType::MsgApp || t == MessageType::MsgHeartbeat ||
            t == MessageType::MsgSnap) {
            Message resp;
            resp.type = (t == MessageType::MsgApp)        ? MessageType::MsgAppResp
                      : (t == MessageType::MsgHeartbeat)  ? MessageType::MsgHeartbeatResp
                      : MessageType::MsgAppResp;
            resp.to   = m.from;
            resp.from = id_;
            resp.term = term_;
            resp.reject = true;
            send(resp);
        } else if (t == MessageType::MsgVote || t == MessageType::MsgPreVote) {
            Message resp;
            resp.type = (t == MessageType::MsgVote) ? MessageType::MsgVoteResp
                                                   : MessageType::MsgPreVoteResp;
            resp.to   = m.from;
            resp.from = id_;
            resp.term = term_;
            resp.reject = true;
            send(resp);
        }
        return;
    }

    // --- Dispatch by role ---
    switch (role_) {
        case Role::Leader:      stepLeader(m);    break;
        case Role::Candidate:   stepCandidate(m); break;
        case Role::PreCandidate: stepCandidate(m); break;
        case Role::Follower:    stepFollower(m);  break;
    }
}

bool RawNode::propose(const std::vector<uint8_t>& data) {
    if (role_ != Role::Leader) {
        return false;
    }
    Entry e;
    e.term  = term_;
    e.index = log_.lastIndex() + 1;
    e.type  = EntryType::Normal;
    e.data  = data;
    log_.append({e});

    // Leader's own progress: it has the entry by definition.
    auto& self = pr_[id_];
    self.matchIndex = log_.lastIndex();
    self.nextIndex  = self.matchIndex + 1;

    broadcastAppend();
    return true;
}

bool RawNode::readIndex(const std::vector<uint8_t>& ctx) {
    if (role_ != Role::Leader) return false;
    if (ctx.empty()) return false;

    // Register the read at the current commit index.
    readOnly_.add(log_.commitIndex(), ctx);

    // For Safe mode: broadcast a heartbeat with the context so followers
    // can ack. For LeaseBased: no quorum check needed.
    if (readOnly_.option() == ReadOnlyOption::Safe) {
        for (auto& [id, pr] : pr_) {
            if (id == id_) continue;
            Message m;
            m.type    = MessageType::MsgHeartbeat;
            m.to      = id;
            m.from    = id_;
            m.term    = term_;
            m.commit  = log_.commitIndex();
            m.context = ctx;
            send(m);
        }
    }
    return true;
}

// ============================================================
// Ready protocol
// ============================================================

bool RawNode::hasReady() const {
    // Unstable entries need persisting.
    // Outgoing messages need sending.
    // Committed entries need applying.
    // (We can't call non-const methods here, so we check buffers.)
    return true; // The app polls() unconditionally each loop iteration;
                  // poll() returns an empty Ready if there's nothing to do.
}

Ready RawNode::poll() {
    Ready rd;

    rd.entries = log_.unstableEntries();
    if (!rd.entries.empty()) {
        lastReadyLastIndex_ = rd.entries.back().index;
    }

    rd.hardState = makeHardState(term_, vote_, log_.commitIndex());

    collectMessages(rd);

    rd.committedEntries = log_.nextCommittedEntries(/*allowConfChange=*/true);
    if (!rd.committedEntries.empty()) {
        lastReadyApplied_ = rd.committedEntries.back().index;
    }

    // Hand off any pending ReadStates to the app.
    rd.readStates = std::move(readStates_);
    readStates_.clear();

    return rd;
}

void RawNode::advance() {
    // Confirm persisted entries.
    if (lastReadyLastIndex_ > 0) {
        log_.stableTo(lastReadyLastIndex_, log_.term(lastReadyLastIndex_));
        lastReadyLastIndex_ = 0;
    }
    // Confirm applied entries.
    if (lastReadyApplied_ > 0) {
        log_.appliedTo(lastReadyApplied_);
        lastReadyApplied_ = 0;
    }
}

// ============================================================
// Role transitions
// ============================================================

void RawNode::becomeFollower(Term term, NodeId lead) {
    role_ = Role::Follower;
    term_ = term;
    lead_ = lead;
    vote_ = 0;
    votes_.clear();
    tickCount_ = 0;
    // Re-randomize election timeout.
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<uint32_t> dist(electionTick_, 2 * electionTick_);
    randomizedElectionTick_ = dist(gen);
    readOnly_.reset();
}

void RawNode::becomeCandidate() {
    role_ = Role::Candidate;
    term_ += 1;
    lead_ = 0;
    vote_ = id_;
    votes_.clear();
    votes_.push_back(id_);  // vote for self
    tickCount_ = 0;
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<uint32_t> dist(electionTick_, 2 * electionTick_);
    randomizedElectionTick_ = dist(gen);
    readOnly_.reset();
}

void RawNode::becomePreCandidate() {
    // PreVote: don't increment term or update vote.
    role_ = Role::PreCandidate;
    lead_ = 0;
    votes_.clear();
    votes_.push_back(id_);
    tickCount_ = 0;
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<uint32_t> dist(electionTick_, 2 * electionTick_);
    randomizedElectionTick_ = dist(gen);
}

void RawNode::becomeLeader() {
    role_ = Role::Leader;
    lead_ = id_;
    tickCount_ = 0;

    // Initialize per-peer progress: nextIndex = lastIndex + 1, matchIndex = 0.
    pr_.clear();
    for (auto id : voters_) {
        bool isLearner = std::find(learners_.begin(), learners_.end(), id) != learners_.end();
        pr_[id] = Progress(maxInflightMsgs_, isLearner);
        pr_[id].reset(log_.lastIndex());
    }
    // Leader's own progress: it has the whole log.
    pr_[id_].matchIndex = log_.lastIndex();
    pr_[id_].nextIndex  = log_.lastIndex() + 1;
    pr_[id_].becomeReplicate();

    // Append a no-op entry so uncommitted entries from previous terms
    // can be committed (Figure 8). Not strictly required if log is empty.
    if (log_.lastIndex() >= log_.firstIndex()) {
        Entry noop;
        noop.term  = term_;
        noop.index = log_.lastIndex() + 1;
        noop.type  = EntryType::Normal;
        log_.append({noop});
        pr_[id_].matchIndex = log_.lastIndex();
        pr_[id_].nextIndex  = log_.lastIndex() + 1;
    }

    // Immediately start replicating to followers.
    broadcastAppend();
}

// ============================================================
// Election
// ============================================================

void RawNode::campaign() {
    becomeCandidate();
    if (quorum() == 1) {
        becomeLeader();
        return;
    }
    for (auto id : voters_) {
        if (id == id_) continue;
        Message m;
        m.type    = MessageType::MsgVote;
        m.to      = id;
        m.from    = id_;
        m.term    = term_;
        m.logTerm = log_.lastTerm();
        m.index   = log_.lastIndex();
        send(m);
    }
}

void RawNode::pollVote(NodeId from, bool granted) {
    // Dedup: a node voting twice doesn't count twice.
    if (std::find(votes_.begin(), votes_.end(), from) != votes_.end()) {
        return;
    }
    if (granted) {
        votes_.push_back(from);
        if (votes_.size() >= quorum()) {
            becomeLeader();
        }
    }
}

// ============================================================
// Replication (leader)
// ============================================================

void RawNode::broadcastAppend() {
    for (auto& [id, pr] : pr_) {
        if (id == id_) continue;
        sendAppend(id);
    }
}

void RawNode::sendAppend(NodeId to) {
    auto it = pr_.find(to);
    if (it == pr_.end()) return;
    Progress& pr = it->second;

    // Don't send if paused (Probe state waiting for ack, or snapshot in flight).
    if (pr.paused) return;
    if (pr.state == ProgressState::Snapshot) {
        sendSnapshot(to);
        return;
    }

    Index next = pr.nextIndex;
    if (next < log_.firstIndex()) {
        // Follower needs a snapshot.
        sendSnapshot(to);
        return;
    }

    // Slice entries [next, lastIndex+1), bounded by maxSizePerMsg.
    std::vector<Entry> ents;
    try {
        ents = log_.slice(next, log_.lastIndex() + 1, maxSizePerMsg_);
    } catch (const std::exception&) {
        sendSnapshot(to);
        return;
    }

    // In Probe state, send even if empty — this lets the follower reject
    // if it has divergent entries, so the leader can decrement nextIndex.
    // In Replicate state, skip empty appends (nothing new to send).
    if (ents.empty() && pr.state != ProgressState::Probe) return;

    // Track in-flight for flow control (Replicate state).
    if (pr.state == ProgressState::Replicate && !ents.empty()) {
        if (pr.inflights.full()) return;  // backpressure
        pr.inflights.add(ents.back().index);
    }

    Message m;
    m.type        = MessageType::MsgApp;
    m.to          = to;
    m.from        = id_;
    m.term        = term_;
    m.logTerm     = log_.term(next - 1);  // prevLogTerm
    m.index       = next - 1;              // prevLogIndex
    m.commit      = log_.commitIndex();
    m.entries     = std::move(ents);

    // In Probe state, send one batch then pause until ack.
    if (pr.state == ProgressState::Probe) {
        pr.paused = true;
    }

    send(m);
}

void RawNode::broadcastHeartbeat() {
    for (auto& [id, pr] : pr_) {
        if (id == id_) continue;
        sendHeartbeat(id);
    }
}

void RawNode::sendHeartbeat(NodeId to) {
    Message m;
    m.type  = MessageType::MsgHeartbeat;
    m.to    = to;
    m.from  = id_;
    m.term  = term_;
    m.commit = log_.commitIndex();
    send(m);
}

void RawNode::sendSnapshot(NodeId to) {
    auto it = pr_.find(to);
    if (it == pr_.end()) return;
    Progress& pr = it->second;

    Snapshot snap;
    try {
        snap = log_.snapshot();
    } catch (const std::exception&) {
        return;
    }
    if (snap.index == 0) return;  // no snapshot available

    pr.becomeSnapshot(snap.index);

    Message m;
    m.type     = MessageType::MsgSnap;
    m.to       = to;
    m.from     = id_;
    m.term     = term_;
    m.snapshot = std::move(snap);
    send(m);
}

bool RawNode::maybeCommit() {
    // Commit rule: find the largest N such that majority of matchIndex >= N,
    // and the entry at N is from the current term (Figure 8).
    std::vector<Index> matches;
    for (auto& [id, pr] : pr_) {
        if (id == id_) {
            matches.push_back(log_.lastIndex());
        } else {
            matches.push_back(pr.matchIndex);
        }
    }
    std::sort(matches.begin(), matches.end(), std::greater<Index>{});

    // matches is sorted descending. The element at index (quorum-1) is the
    // largest N such that at least quorum nodes have matchIndex >= N.
    Index n = matches[quorum() - 1];
    if (n > log_.commitIndex() && log_.term(n) == term_) {
        log_.maybeCommit(n, term_);
        return true;
    }
    return false;
}

void RawNode::restore(const Snapshot& snap) {
    log_.restore(snap);
    // Reset all peer progress to start after the snapshot.
    for (auto& [id, pr] : pr_) {
        if (id == id_) {
            pr.matchIndex = snap.index;
            pr.nextIndex  = snap.index + 1;
        } else {
            pr.reset(snap.index);
        }
    }
}

// ============================================================
// stepLeader
// ============================================================

void RawNode::stepLeader(const Message& m) {
    switch (m.type) {
        case MessageType::MsgPropose: {
            // A local proposal (forwarded from a follower or directly).
            propose(m.entries.empty() ? std::vector<uint8_t>{} : m.entries[0].data);
            break;
        }
        case MessageType::MsgAppResp: {
            auto it = pr_.find(m.from);
            if (it == pr_.end()) break;
            Progress& pr = it->second;

            if (m.reject) {
                // Follower rejected: decrement nextIndex using the hint.
                pr.maybeDecrFromRejectHint(m.index, m.rejectHint);
                pr.becomeProbe();
                sendAppend(m.from);
            } else {
                // Follower accepted: update matchIndex.
                pr.update(m.index);
                if (pr.state == ProgressState::Probe) {
                    pr.becomeReplicate();
                }
                // Try to commit.
                if (maybeCommit()) {
                    broadcastAppend();
                }
                // Keep pipelining.
                if (pr.state == ProgressState::Replicate) {
                    sendAppend(m.from);
                }
            }
            break;
        }
        case MessageType::MsgHeartbeatResp: {
            // Ack for a heartbeat. Also use it as a trigger to send
            // AppendEntries if the peer is behind (catch-up probe).
            {
                auto it = pr_.find(m.from);
                if (it == pr_.end()) break;
                Progress& pr = it->second;
                if (pr.state == ProgressState::Replicate) {
                    sendAppend(m.from);
                } else if (pr.state == ProgressState::Probe && !pr.paused) {
                    sendAppend(m.from);
                }
            }

            // ReadIndex: if this heartbeat resp carries a read context,
            // record the ack. When quorum is reached, emit a ReadState.
            if (!m.context.empty()) {
                auto ackIndex = readOnly_.recvAck(m, quorum());
                if (ackIndex.has_value()) {
                    // Quorum reached. Advance and emit ReadState for this
                    // and all earlier pending requests (same heartbeat round).
                    auto ctx = m.context;
                    auto idx = readOnly_.advance(ctx);
                    if (idx.has_value()) {
                        ReadState rs;
                        rs.index = *idx;
                        rs.requestCtx = ctx;
                        readStates_.push_back(rs);

                        // Reply to the original requestor (if a follower asked).
                        auto rit = readRequestors_.find(ctx);
                        if (rit != readRequestors_.end()) {
                            NodeId to = rit->second;
                            readRequestors_.erase(rit);
                            Message resp;
                            resp.type    = MessageType::MsgReadIndexResp;
                            resp.to      = to;
                            resp.from    = id_;
                            resp.term    = term_;
                            resp.index   = *idx;
                            resp.context = ctx;
                            send(resp);
                        }
                    }
                }
            }
            break;
        }
        case MessageType::MsgReadIndex: {
            // A follower (or local client) wants a linearizable read.
            // Register the request and broadcast a heartbeat with the context.
            if (m.context.empty()) break;
            readOnly_.add(log_.commitIndex(), m.context);
            // Remember who asked so we can reply later.
            if (m.from != id_) {
                readRequestors_[m.context] = m.from;
            }
            // Broadcast heartbeat with the read context.
            if (readOnly_.option() == ReadOnlyOption::Safe) {
                for (auto& [id, pr] : pr_) {
                    if (id == id_) continue;
                    Message hb;
                    hb.type    = MessageType::MsgHeartbeat;
                    hb.to      = id;
                    hb.from    = id_;
                    hb.term    = term_;
                    hb.commit  = log_.commitIndex();
                    hb.context = m.context;
                    send(hb);
                }
            }
            break;
        }
        case MessageType::MsgTransferLeader:
            // TODO: leadership transfer.
            break;
        case MessageType::MsgVote:
        case MessageType::MsgPreVote:
            // We're leader in this term; a vote request in a lower or equal
            // term should be denied (already handled by term check). If it
            // has a higher term, step() already demoted us.
            break;
        default:
            break;
    }
}

// ============================================================
// stepCandidate (also used for PreCandidate)
// ============================================================

void RawNode::stepCandidate(const Message& m) {
    switch (m.type) {
        case MessageType::MsgVoteResp:
        case MessageType::MsgPreVoteResp: {
            pollVote(m.from, !m.reject);
            break;
        }
        case MessageType::MsgApp:
        case MessageType::MsgHeartbeat:
        case MessageType::MsgSnap: {
            // A leader from the same or higher term is contacting us. Step down.
            // (Term check in step() already handled higher terms; same term means
            // another candidate won and is now leader.)
            if (m.term == term_) {
                becomeFollower(m.term, m.from);
            }
            // Process the message as a follower.
            stepFollower(m);
            break;
        }
        case MessageType::MsgTimeoutNow: {
            // Leadership transfer: start a new election.
            campaign();
            break;
        }
        default:
            break;
    }
}

// ============================================================
// stepFollower
// ============================================================

void RawNode::stepFollower(const Message& m) {
    switch (m.type) {
        case MessageType::MsgPropose: {
            // Forward to the leader (or reject if no leader known).
            if (lead_ == 0) break;
            Message fwd = m;
            fwd.to = lead_;
            send(fwd);
            break;
        }
        case MessageType::MsgApp: {
            // AppendEntries RPC (Section 5.3).
            lead_ = m.from;
            tickCount_ = 0;  // reset election timer (paper §5.2)
            bool ok = log_.maybeAppend(m.index, m.logTerm, m.commit, m.entries);
            Message resp;
            resp.type    = MessageType::MsgAppResp;
            resp.to      = m.from;
            resp.from    = id_;
            resp.term    = term_;
            resp.reject   = !ok;
            if (ok) {
                resp.index = m.index + m.entries.size();  // matchIndex
            } else {
                // Hint: our last index (so leader can decrement nextIndex).
                resp.index      = m.index;
                resp.rejectHint = log_.lastIndex();
            }
            send(resp);
            break;
        }
        case MessageType::MsgHeartbeat: {
            // Heartbeat: update leader and commit index.
            lead_ = m.from;
            tickCount_ = 0;  // reset election timer (paper §5.2)
            if (m.commit > log_.commitIndex()) {
                log_.commitTo(m.commit);
            }
            Message resp;
            resp.type = MessageType::MsgHeartbeatResp;
            resp.to   = m.from;
            resp.from = id_;
            resp.term = term_;
            send(resp);
            break;
        }
        case MessageType::MsgSnap: {
            // InstallSnapshot (Section 7).
            lead_ = m.from;
            tickCount_ = 0;  // reset election timer
            restore(m.snapshot);
            Message resp;
            resp.type = MessageType::MsgAppResp;
            resp.to   = m.from;
            resp.from = id_;
            resp.term = term_;
            resp.index = m.snapshot.index;  // accepted up to snapshot
            send(resp);
            break;
        }
        case MessageType::MsgVote:
        case MessageType::MsgPreVote: {
            // RequestVote (Section 5.2): grant if we haven't voted for someone
            // else this term, and the candidate's log is at least as up-to-date.
            bool logUpToDate = (m.logTerm >  log_.lastTerm()) ||
                              (m.logTerm == log_.lastTerm() && m.index >= log_.lastIndex());
            bool grant = (vote_ == 0 || vote_ == m.from) && logUpToDate;

            Message resp;
            resp.type   = (m.type == MessageType::MsgVote) ? MessageType::MsgVoteResp
                                                          : MessageType::MsgPreVoteResp;
            resp.to     = m.from;
            resp.from   = id_;
            resp.term   = term_;
            resp.reject = !grant;
            send(resp);

            if (grant && m.type == MessageType::MsgVote) {
                vote_ = m.from;
                tickCount_ = 0;  // reset election timer
            }
            break;
        }
        case MessageType::MsgReadIndex: {
            // Forward to leader (or handle locally if we are leader — but we're follower).
            if (lead_ == 0) break;
            Message fwd = m;
            fwd.to = lead_;
            send(fwd);
            break;
        }
        case MessageType::MsgReadIndexResp: {
            // Leader confirmed we can read at index m.index. Emit a ReadState
            // so the app waits for appliedIndex >= index, then serves the read.
            ReadState rs;
            rs.index = m.index;
            rs.requestCtx = m.context;
            readStates_.push_back(rs);
            break;
        }
        case MessageType::MsgTimeoutNow: {
            // Leadership transfer: start election immediately.
            campaign();
            break;
        }
        default:
            break;
    }
}

// ============================================================
// Message buffering + collection
// ============================================================

void RawNode::send(const Message& m) {
    if (isLocalMsg(m.type)) {
        // Local messages are fed back into step() immediately (deterministic).
        // For simplicity, we queue them like normal messages; the app's
        // transport layer will know to call step() instead of sending over wire.
    }
    msgs_.push_back(m);
}

void RawNode::collectMessages(Ready& rd) {
    rd.messages = std::move(msgs_);
    msgs_.clear();
}

// ============================================================
// Helpers + observability
// ============================================================

std::size_t RawNode::quorum() const {
    return voters_.size() / 2 + 1;
}

Role   RawNode::role() const      { return role_; }
Term   RawNode::term() const      { return term_; }
NodeId RawNode::lead() const      { return lead_; }
NodeId RawNode::id() const        { return id_; }

const std::map<NodeId, tracker::Progress>& RawNode::progress() const {
    return pr_;
}

Index RawNode::lastIndex() const {
    return log_.lastIndex();
}

Term RawNode::entryTerm(Index i) const {
    return log_.term(i);
}

} // namespace raft
